### ISSUE TITLE
Tracking inspector is unable to load Tracking_Result folder

### ISSUE THREAD

**Issue by hkrishnan007** [FastTrackOrg/FastTrack#19]
The tracking inspector is unable to load the Tracking_Result folder as the folder option remains inactive.

**Comment by bgallois** [comment]
The current behavior is that the "Open Tracking_Result directory" button remains inactive until a movie is loaded using the "Open" button. @hkrishnan007 if you observe a different behavior please provide a series of actions in order to reproduce the error, otherwise updating the documentation should be sufficient.

**Comment by hkrishnan007** [comment]
Great..Thanks!

**Comment by bgallois** [comment]
Closed with 4fa9b580311ec15fb8edf96666e377438e438b1a.
